###
POST http://localhost:8080/pwd/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

{
  "user_id": "1",
  "resource":"yandex.ru",
  "login":"admin",
  "password":"12345"
}

###
DELETE http://localhost:8080/pwd/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

{
  "user_id": "1",
  "resource":"yandex.ru"
}