###
POST http://localhost:8080/card/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

{
  "title": "My Password",
  "description": "This is my email password",
  "number": "number",
  "pincode": "pin code",
  "cvv": "cvv",
  "expire": "tomorrow"
}

###
POST http://localhost:8080/card/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

{
  "user_id": 1,
  "text_id": "1"
}

###
POST http://localhost:8080/card/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

{
  "user_id": 1
}

###
GET http://localhost:8080/card/get/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

###
POST http://localhost:8080/card/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

{
  "title": "My C",
  "description": "This is my C",
  "number": "number",
  "pincode": "pin code",
  "cvv": "cvv",
  "expire": "tomorrow"
}