###
POST http://localhost:8080/pwd/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

{
  "title": "My Password",
  "description": "This is my email password",
  "credentials": {
    "login": "myemail@example.com",
    "password": "mypassword123"
  }
}

###
POST http://localhost:8080/pwd/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

{
  "user_id": 1,
  "pwd_id": "100"
}

###
POST http://localhost:8080/pwd/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

{
  "user_id": 1
}

###
GET http://localhost:8080/pwd/get/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

###
POST http://localhost:8080/pwd/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjF9.X2KuV_6nTWk5ysPSjZ3DQe-eSn8QLiYv5qmyx93S2iE

{
  "pwd_id": "100",
  "title": "My Password",
  "description": "This is my email password",
  "credentials": {
    "login": "myemail@example.com",
    "password": "mypassword456"
  }
}